name: CI

on:
  - push
  - pull_request

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Skip Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          concurrent_skipping: "same_content"
          paths_ignore: '[".vscode/", "**/docs/**", "**/*.md"]'
          do_not_skip: '["pull_request"]'

  lint:
    name: Linting Checks
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Linting Checks
        run: yarn lint

      - name: Check spelling
        run: yarn check-spelling
